#ifndef LIGHTMODULE_GLOBAL_H
#define LIGHTMODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LIGHTMODULE_LIB
# define LIGHTMODULE_EXPORT Q_DECL_EXPORT
#else
# define LIGHTMODULE_EXPORT Q_DECL_IMPORT
#endif

#define _MAX_CHDATA_NUM 8

#define _CHN_NUM 6

#endif // LIGHTMODULE_GLOBAL_H
