#ifndef BARCODEREADER_GLOBAL_H
#define BARCODEREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BARCODEREADER_LIB
# define BARCODEREADER_EXPORT Q_DECL_EXPORT
#else
# define BARCODEREADER_EXPORT Q_DECL_IMPORT
#endif

#endif // BARCODEREADER_GLOBAL_H
